#개발 환결 설정
server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: postgres
    password: mypassword

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: debug